[package]
name = "dtools"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "glove80-flash"
path = "src/bin/glove80_flash.rs"

[dependencies]
anyhow = "1"
itertools = "0.11"
xflags = "0.3"
xshell = "0.2"
